import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://127.0.0.1:3001/t');
  await page.getByRole('button', { name: 'Prescriptions' }).click();
  await page.getByRole('button', { name: 'Add Record' }).click();
  await page.getByRole('textbox', { name: 'Medication Name *' }).fill('Prednisone');
  await page.getByRole('textbox', { name: 'Medication Name *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Dose' }).fill('10mg');
  await page.getByRole('textbox', { name: 'Dose' }).press('Tab');
  await page.getByRole('textbox', { name: 'Frequency' }).fill('once daily');
  await page.getByRole('combobox').click();
  await page.getByRole('option', { name: 'Active' }).click();
  await page.getByRole('textbox', { name: 'Start Date' }).fill('2025-11-27');
  await page.getByRole('textbox', { name: 'Start Date' }).press('Tab');
  await page.getByRole('button', { name: 'Create' }).click();
  await expect(page.getByRole('heading', { name: 'Prednisone' })).toBeVisible();
  await expect(page.getByRole('paragraph').filter({ hasText: 'Prednisone' })).toBeVisible();
  await expect(page.getByText('active')).toBeVisible();
  await expect(page.getByText('once daily')).toBeVisible();
  await expect(page.getByText('10mg')).toBeVisible();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(1).click();
  await page.getByRole('textbox', { name: 'Medication Name *' }).click();
  await page.getByRole('textbox', { name: 'Medication Name *' }).fill('Prednisoner');
  await page.getByRole('textbox', { name: 'Dose' }).click();
  await page.getByRole('textbox', { name: 'Dose' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Dose' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Dose' }).fill('12mg');
  await page.getByRole('textbox', { name: 'Frequency' }).click();
  await page.getByRole('textbox', { name: 'Frequency' }).click();
  await page.getByRole('textbox', { name: 'Frequency' }).press('Alt+ArrowLeft');
  await page.getByRole('textbox', { name: 'Frequency' }).press('Alt+ArrowLeft');
  await page.getByRole('textbox', { name: 'Frequency' }).press('Alt+Shift+ArrowRight');
  await page.getByRole('textbox', { name: 'Frequency' }).fill('twice daily');
  await page.getByRole('textbox', { name: 'Stop Date' }).fill('2025-12-27');
  await page.getByRole('combobox').click();
  await page.getByLabel('Stopped').getByText('Stopped').click();
  await page.getByRole('button', { name: 'Update' }).click();
  await expect(page.getByRole('heading', { name: 'Prednisoner' })).toBeVisible();
  await expect(page.getByRole('paragraph').filter({ hasText: 'Prednisoner' })).toBeVisible();
  await expect(page.getByText('12mg')).toBeVisible();
  await expect(page.getByText('twice daily')).toBeVisible();
  await expect(page.getByText('stopped')).toBeVisible();
  await expect(page.getByText('11/27/2025', { exact: true })).toBeVisible();
  await expect(page.getByText('12/27/')).toBeVisible();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(2).click();
  await page.getByRole('button', { name: 'Delete' }).click();
  await expect(page.getByText('No records yet. Connect the AC130 MCP to an LLM assistant to add records.MCP')).toBeVisible();
});